### ISSUE TITLE
想问下写cpp Netty 的初衷是什么

### ISSUE THREAD

**Issue by chanchann** [CppNetty/CppNetty#1]
Netty 是个很好的库，但是想了解下，cpp重写netty有何意义，相对于c++其他框架有何优势好特点呢

**Comment by ghost** [comment]
哈哈，你直接一问，把大佬干无语了。然后他去整了个牛逼的新框架。 libhv

虽然不叫CppNetty，但我看超越了Netty。

**Comment by chanchann** [comment]
> 哈哈，你直接一问，把大佬干无语了。然后他去整了个牛逼的新框架。 libhv
> 
> 虽然不叫CppNetty，但我看超越了Netty。

cppnetty是后面才开的库，libhv早就有了，我都用libhv好久了，我就是很好奇为啥大佬搞了这么牛逼的库，还开了个重写的新坑

**Comment by ghost** [comment]
想写就写，不写就不写，哪有那么多戏

**Comment by chanchann** [comment]
> 

那不就交流一下，万一可以跟大佬学一波呢

**Comment by ghost** [comment]
估计大佬时薪1000美金上下，哪有时间交流。。。
